# Check for plugin updates on startup
check-for-updates: true

# The Captcha Settings

fishing-captcha:
  # Amount of times a player can fish until a captcha appears
  fish-caught-until-captcha: 5

  # The item the player must click to verify
  captcha-item: 'EMERALD'
  
  # The filler item for the inventory (leave blank for no item)
  filler-item: ''

  # UI settings
  inventory-name: "Security Check: Click the Emerald!"
  inventory-size: 36
  
  # How many times they can fail the captcha before being kicked
  max-failed-attempts: 3